version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personalized_recommendation_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

    
